version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.10.0

    steps:
      - checkout
      - run:
          name: Setup NPM Token
          command: |
            npm config set \
              "//registry.npmjs.org/:_authToken=$NPM_TOKEN" \
              "registry=https://registry.npmjs.org/"
      - run:
          name: Corepack enable
          command: sudo corepack enable
      - run:
          name: Install Dependencies
          command: pnpm install --no-frozen-lockfile
      - run:
          name: build
          command: pnpm run vscode:prepublish
      - run:
          name: release
          command: pnpm run semantic-release
